=== renmeng8875/projects/mybatis-sharding/src/main/java/cannon/mybatis/sharding/plugin/mybatis-sharding-db.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns="http://fangjialong.iteye.com/schema/mybatis-sharding"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://fangjialong.iteye.com/schema/mybatis-sharding">
	<xsd:annotation>
		<xsd:documentation>
			<![CDATA[
				数据库集群配置
			]]>
		</xsd:documentation>
	</xsd:annotation>

	<!-- Top-level <databases> tag -->
	<xsd:element name="databases">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="logicName" minOccurs="1" maxOccurs="1" />
				<xsd:element ref="configs" minOccurs="0" maxOccurs="1" />
				<xsd:element ref="database" minOccurs="1" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="logicName">
		<xsd:annotation>
			<xsd:documentation>
				<![CDATA[
					数据库集群逻辑名称
				]]>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:attribute name="value" use="required" type="xsd:string"></xsd:attribute>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="configs">
		<xsd:annotation>
			<xsd:documentation>
				<![CDATA[
					数据库集群全局配置
				]]>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="property" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="property">
		<xsd:complexType>
			<xsd:attribute name="name" use="required" type="xsd:string"></xsd:attribute>
			<xsd:attribute name="value" use="required" type="xsd:string"></xsd:attribute>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="database">
		<xsd:annotation>
			<xsd:documentation>
				<![CDATA[
					数据库配置
				]]>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType mixed="true">
			<xsd:sequence>
				<xsd:element ref="property" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="suffix" use="required" type="xsd:string"></xsd:attribute>
			<xsd:attribute name="username" use="required" type="xsd:string"></xsd:attribute>
			<xsd:attribute name="password" use="required" type="xsd:string"></xsd:attribute>
			<xsd:attribute name="jdbcUrl" use="required" type="xsd:string"></xsd:attribute>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== renmeng8875/projects/mybatis-sharding/src/test/java/META-INF/database/distributed-default-db.xml
<?xml version="1.0" encoding="UTF-8"?>
<databases xmlns="http://fangjialong.iteye.com/schema/mybatis-sharding"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://fangjialong.iteye.com/schema/mybatis-sharding
	http://fangjialong.iteye.com/schema/mybatis-sharding/mybatis-sharding-db.xsd">
	<!-- 全局配置 -->
	<logicName value="test" />
	<configs>
		<property name="minPoolSize" value="4" />
		<property name="minPoolSize" value="8" />
		<property name="driverClass" value="com.mysql.jdbc.Driver" />
		<property name="maxIdleTime" value="900" />
		<property name="idleConnectionTestPeriod" value="1800" />
	</configs>
	<database suffix="_00" username="root" password="123456"
		jdbcUrl="jdbc:mysql://localhost:3306/test_00?useUnicode=true&amp;characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull">
		<property name="minPoolSize" value="4" />
		<property name="minPoolSize" value="8" />
		<property name="driverClass" value="com.mysql.jdbc.Driver" />
		<property name="maxIdleTime" value="900" />
		<property name="idleConnectionTestPeriod" value="1800" />
	</database>
	<database suffix="_01" username="root" password="123456"
		jdbcUrl="jdbc:mysql://localhost:3306/test_01?useUnicode=true&amp;characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull" />
</databases>
