<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mottos [
<!ELEMENT mottos (motto)+>
<!ELEMENT motto (#PCDATA)>
<!ATTLIST motto 
man CDATA #REQUIRED
id ID #REQUIRED
>
]>
<mottos>
<motto id="m1" man="柏格森">真正的谦虚只能是对虚荣心进行了深思以后的产物</motto>
<motto id="m2" man="法拉第">像蜡烛为人照明那样，有一分热，发一分光，忠诚而踏实地为人类伟大事业贡献自己的力量</motto><motto id="m3" man="勒努维耶">世界因为缺乏对超验真理的信仰而备受折磨！</motto><motto id="m4" man="斯宾诺莎">对于情感的理解愈多，则愈能控制情感，而心灵感受情感的痛苦也愈少</motto><motto id="m5" man="斯宾诺莎">害羞是畏惧或害怕羞辱的情绪，这种情绪可以阻止人不去犯某些卑鄙的行为</motto><motto id="m6" man="斯宾诺莎">不嘲笑、不悲伤、但求理解</motto><motto id="m7" man="斯宾诺莎">正如光既暴露了自身，又暴露了周围的黑暗一样，真理既是自身的标准，又是虚假的标准</motto><motto id="m8" man="斯宾诺莎">自由人最少想到死，他的智慧不是关于死的默念，而是对于生的沉思</motto><motto id="m9" man="斯宾诺莎">希望与恐惧的情感本身不可能是善的</motto><motto id="m10" man="孔子">不患人之不己知,患不知人也</motto><motto id="m11" man="孔子">不迁怒，不贰过</motto><motto id="m12" man="孔子">与朋友交，严而有信</motto><motto id="m13" man="罗素">对爱情的渴望，对知识的追求，对人类苦难不可遏制的同情心，这三种纯洁而无比强烈的激情支配着我的一生</motto><motto id="m14" man="罗素">良好的人生是受行动和智慧指导的</motto><motto id="m15" man="罗素">幸福的生活是一种由爱鼓舞，由知识指导的生活</motto><motto id="m16" man="罗素">喝醉是暂时性的自杀</motto><motto id="m17" man="罗素">不要害怕怀有怪念头，因为现在人们接受的所有的观念都曾经是怪念头</motto><motto id="m18" man="罗素">民主，就是挑选那个受批评的人的过程</motto><motto id="m19" man="罗素">喝醉是暂时性的自杀</motto><motto id="m20" man="罗素">我永远不会为信仰而死，因为我的信仰可能是错的</motto><motto id="m21" man="罗素">据说人是一种理性动物。穷我自己一生，我都在寻找这观点的证据</motto><motto id="m22" man="罗素">人是轻信的动物，必须得相信点什么。如果这种信仰没有什么好的依据，糟糕的依据也能对付</motto><motto id="m23" man="罗素">人生而无知，但还不愚蠢。教育才把他们变蠢</motto><motto id="m24" man="罗素">传统的人看到背离传统的行为就大发雷霆，主要是因为他们把这种背离当作对他们的批评</motto><motto id="m25" man="罗素">幻觉不是你的错，在幻觉中做决定，这就是你的不对了</motto><motto id="m26" man="罗素">对幸福的轻蔑通常是对其他人幸福的轻蔑，在精巧的伪装之下是对人类的仇恨</motto><motto id="m27" man="王尔德">经验是每个人为其错误寻找的代名词</motto><motto id="m28" man="富兰克林">经验始终是收费高的学校，然而，笨汉非进此学校不可</motto><motto id="m29" man="罗素">从错误中吸取教训是教育极为重要的一部分</motto><motto id="m30" man="爱因斯坦">凡在小事上对真理持轻率态度的人，在大事上也是不足信的</motto><motto id="m31" man="周兴嗣">天地玄黄</motto><motto id="m32" man="周兴嗣">宇宙洪荒</motto><motto id="m33" man="周兴嗣">日月盈昃</motto><motto id="m34" man="周兴嗣">辰宿列张</motto><motto id="m35" man="周兴嗣">寒来暑往</motto><motto id="m36" man="周兴嗣">秋收冬藏</motto><motto id="m37" man="周兴嗣">闰馀成岁</motto><motto id="m38" man="周兴嗣">律吕调阳</motto><motto id="m39" man="周兴嗣">云腾致雨</motto><motto id="m40" man="周兴嗣">露结为霜</motto><motto id="m41" man="周兴嗣">金生丽水</motto><motto id="m42" man="周兴嗣">玉出昆冈</motto><motto id="m43" man="周兴嗣">剑号巨阙</motto><motto id="m44" man="周兴嗣">珠称夜光</motto><motto id="m45" man="周兴嗣">果珍李柰</motto><motto id="m46" man="周兴嗣">菜重芥姜</motto><motto id="m47" man="周兴嗣">海咸河淡</motto><motto id="m48" man="周兴嗣">鳞潜羽翔</motto><motto id="m49" man="周兴嗣">龙师火帝</motto><motto id="m50" man="周兴嗣">鸟官人皇</motto><motto id="m51" man="周兴嗣">始制文字</motto><motto id="m52" man="周兴嗣">乃服衣裳</motto><motto id="m53" man="周兴嗣">推位让国</motto><motto id="m54" man="周兴嗣">有虞陶唐</motto><motto id="m55" man="周兴嗣">吊民伐罪</motto><motto id="m56" man="周兴嗣">周发殷汤</motto><motto id="m57" man="周兴嗣">坐朝问道</motto><motto id="m58" man="周兴嗣">垂拱平章</motto><motto id="m59" man="周兴嗣">爱育黎首</motto><motto id="m60" man="周兴嗣">臣伏戎羌</motto><motto id="m61" man="周兴嗣">遐迩一体</motto><motto id="m62" man="周兴嗣">率宾归王</motto><motto id="m63" man="周兴嗣">鸣凤在竹</motto><motto id="m64" man="周兴嗣">白驹食场</motto><motto id="m65" man="周兴嗣">化被草木</motto><motto id="m66" man="周兴嗣">赖及万方</motto><motto id="m67" man="周兴嗣">盖此身发</motto><motto id="m68" man="周兴嗣">四大五常</motto><motto id="m69" man="周兴嗣">恭惟鞠养</motto><motto id="m70" man="周兴嗣">岂敢毁伤</motto><motto id="m71" man="周兴嗣">女慕贞洁</motto><motto id="m72" man="周兴嗣">男效才良</motto><motto id="m73" man="周兴嗣">知过必改</motto><motto id="m74" man="周兴嗣">得能莫忘</motto><motto id="m75" man="周兴嗣">罔谈彼短</motto><motto id="m76" man="周兴嗣">靡恃己长</motto><motto id="m77" man="周兴嗣">信使可覆</motto><motto id="m78" man="周兴嗣">器欲难量</motto><motto id="m79" man="周兴嗣">墨悲丝染</motto><motto id="m80" man="周兴嗣">诗赞羔羊</motto><motto id="m81" man="周兴嗣">景行维贤</motto><motto id="m82" man="周兴嗣">克念作圣</motto><motto id="m83" man="周兴嗣">德建名立</motto><motto id="m84" man="周兴嗣">形端表正</motto><motto id="m85" man="周兴嗣">空谷传声</motto><motto id="m86" man="周兴嗣">虚堂习听</motto><motto id="m87" man="周兴嗣">祸因恶积</motto><motto id="m88" man="周兴嗣">福缘善庆</motto><motto id="m89" man="周兴嗣">尺璧非宝</motto><motto id="m90" man="周兴嗣">寸阴是竞</motto><motto id="m91" man="周兴嗣">资父事君</motto><motto id="m92" man="周兴嗣">曰严与敬</motto><motto id="m93" man="周兴嗣">孝当竭力</motto><motto id="m94" man="周兴嗣">忠则尽命</motto><motto id="m95" man="周兴嗣">临深履薄</motto><motto id="m96" man="周兴嗣">夙兴温凊</motto><motto id="m97" man="周兴嗣">似兰斯馨</motto><motto id="m98" man="周兴嗣">如松之盛</motto><motto id="m99" man="周兴嗣">川流不息</motto><motto id="m100" man="周兴嗣">渊澄取映</motto><motto id="m101" man="周兴嗣">容止若思</motto><motto id="m102" man="周兴嗣">言辞安定</motto><motto id="m103" man="周兴嗣">笃初诚美</motto><motto id="m104" man="周兴嗣">慎终宜令</motto><motto id="m105" man="周兴嗣">荣业所基</motto><motto id="m106" man="周兴嗣">籍甚无竟</motto><motto id="m107" man="周兴嗣">学优登仕</motto><motto id="m108" man="周兴嗣">摄职从政</motto><motto id="m109" man="周兴嗣">存以甘棠</motto><motto id="m110" man="周兴嗣">去而益咏</motto><motto id="m111" man="周兴嗣">乐殊贵贱</motto><motto id="m112" man="周兴嗣">礼别尊卑</motto><motto id="m113" man="周兴嗣">上和下睦</motto><motto id="m114" man="周兴嗣">夫唱妇随</motto><motto id="m115" man="周兴嗣">外受傅训</motto><motto id="m116" man="周兴嗣">入奉母仪</motto><motto id="m117" man="周兴嗣">诸姑伯叔</motto><motto id="m118" man="周兴嗣">犹子比儿</motto><motto id="m119" man="周兴嗣">孔怀兄弟</motto><motto id="m120" man="周兴嗣">同气连枝</motto><motto id="m121" man="周兴嗣">交友投分</motto><motto id="m122" man="周兴嗣">切磨箴规</motto><motto id="m123" man="周兴嗣">仁慈隐恻</motto><motto id="m124" man="周兴嗣">造次弗离</motto><motto id="m125" man="周兴嗣">节义廉退</motto><motto id="m126" man="周兴嗣">颠沛匪亏</motto><motto id="m127" man="周兴嗣">性静情逸</motto><motto id="m128" man="周兴嗣">心动神疲</motto><motto id="m129" man="周兴嗣">守真志满</motto><motto id="m130" man="周兴嗣">逐物意移</motto><motto id="m131" man="周兴嗣">坚持雅操</motto><motto id="m132" man="周兴嗣">好爵自縻</motto><motto id="m133" man="周兴嗣">都邑华夏</motto><motto id="m134" man="周兴嗣">东西二京</motto><motto id="m135" man="周兴嗣">背邙面洛</motto><motto id="m136" man="周兴嗣">浮渭据泾</motto><motto id="m137" man="周兴嗣">宫殿盘郁</motto><motto id="m138" man="周兴嗣">楼观飞惊</motto><motto id="m139" man="周兴嗣">图写禽兽</motto><motto id="m140" man="周兴嗣">画彩仙灵</motto><motto id="m141" man="周兴嗣">丙舍傍启</motto><motto id="m142" man="周兴嗣">甲帐对楹</motto><motto id="m143" man="周兴嗣">肆筵设席</motto><motto id="m144" man="周兴嗣">鼓瑟吹笙</motto><motto id="m145" man="周兴嗣">升阶纳陛</motto><motto id="m146" man="周兴嗣">弁转疑星</motto><motto id="m147" man="周兴嗣">右通广内</motto><motto id="m148" man="周兴嗣">左达承明</motto><motto id="m149" man="周兴嗣">既集坟典</motto><motto id="m150" man="周兴嗣">亦聚群英</motto><motto id="m151" man="周兴嗣">杜稿钟隶</motto><motto id="m152" man="周兴嗣">漆书壁经</motto><motto id="m153" man="周兴嗣">府罗将相</motto><motto id="m154" man="周兴嗣">路侠槐卿</motto><motto id="m155" man="周兴嗣">户封八县</motto><motto id="m156" man="周兴嗣">家给千兵</motto><motto id="m157" man="周兴嗣">高冠陪辇</motto><motto id="m158" man="周兴嗣">驱毂振缨</motto><motto id="m159" man="周兴嗣">世禄侈富</motto><motto id="m160" man="周兴嗣">车驾肥轻</motto><motto id="m161" man="周兴嗣">策功茂实</motto><motto id="m162" man="周兴嗣">勒碑刻铭</motto><motto id="m163" man="周兴嗣">磻溪伊尹</motto><motto id="m164" man="周兴嗣">佐时阿衡</motto><motto id="m165" man="周兴嗣">奄宅曲阜</motto><motto id="m166" man="周兴嗣">微旦孰营</motto><motto id="m167" man="周兴嗣">桓公匡合</motto><motto id="m168" man="周兴嗣">济弱扶倾</motto><motto id="m169" man="周兴嗣">绮回汉惠</motto><motto id="m170" man="周兴嗣">说感武丁</motto><motto id="m171" man="周兴嗣">俊乂密勿</motto><motto id="m172" man="周兴嗣">多士寔宁</motto><motto id="m173" man="周兴嗣">晋楚更霸</motto><motto id="m174" man="周兴嗣">赵魏困横</motto><motto id="m175" man="周兴嗣">假途灭虢</motto><motto id="m176" man="周兴嗣">践土会盟</motto><motto id="m177" man="周兴嗣">何遵约法</motto><motto id="m178" man="周兴嗣">韩弊烦刑</motto><motto id="m179" man="周兴嗣">起翦颇牧</motto><motto id="m180" man="周兴嗣">用军最精</motto><motto id="m181" man="周兴嗣">宣威沙漠</motto><motto id="m182" man="周兴嗣">驰誉丹青</motto><motto id="m183" man="周兴嗣">九州禹迹</motto><motto id="m184" man="周兴嗣">百郡秦并</motto><motto id="m185" man="周兴嗣">岳宗泰岱</motto><motto id="m186" man="周兴嗣">禅主云亭</motto><motto id="m187" man="周兴嗣">雁门紫塞</motto><motto id="m188" man="周兴嗣">鸡田赤城</motto><motto id="m189" man="周兴嗣">昆池碣石</motto><motto id="m190" man="周兴嗣">钜野洞庭</motto><motto id="m191" man="周兴嗣">旷远绵邈</motto><motto id="m192" man="周兴嗣">岩岫杳冥</motto><motto id="m193" man="周兴嗣">治本于农</motto><motto id="m194" man="周兴嗣">务资稼穑</motto><motto id="m195" man="周兴嗣">俶载南亩</motto><motto id="m196" man="周兴嗣">我艺黍稷</motto><motto id="m197" man="周兴嗣">税熟贡新</motto><motto id="m198" man="周兴嗣">劝赏黜陟</motto><motto id="m199" man="周兴嗣">孟轲敦素</motto><motto id="m200" man="周兴嗣">史鱼秉直</motto><motto id="m201" man="周兴嗣">庶几中庸</motto><motto id="m202" man="周兴嗣">劳谦谨敕</motto><motto id="m203" man="周兴嗣">聆音察理</motto><motto id="m204" man="周兴嗣">鉴貌辨色</motto><motto id="m205" man="周兴嗣">贻厥嘉猷</motto><motto id="m206" man="周兴嗣">勉其祗植</motto><motto id="m207" man="周兴嗣">省躬讥诫</motto><motto id="m208" man="周兴嗣">宠增抗极</motto><motto id="m209" man="周兴嗣">殆辱近耻</motto><motto id="m210" man="周兴嗣">林皋幸即</motto><motto id="m211" man="周兴嗣">两疏见机</motto><motto id="m212" man="周兴嗣">解组谁逼</motto><motto id="m213" man="周兴嗣">索居闲处</motto><motto id="m214" man="周兴嗣">沉默寂寥</motto><motto id="m215" man="周兴嗣">求古寻论</motto><motto id="m216" man="周兴嗣">散虑逍遥</motto><motto id="m217" man="周兴嗣">欣奏累遣</motto><motto id="m218" man="周兴嗣">戚谢欢招</motto><motto id="m219" man="周兴嗣">渠荷的历</motto><motto id="m220" man="周兴嗣">园莽抽条</motto><motto id="m221" man="周兴嗣">枇杷晚翠</motto><motto id="m222" man="周兴嗣">梧桐蚤凋</motto><motto id="m223" man="周兴嗣">陈根委翳</motto><motto id="m224" man="周兴嗣">落叶飘摇</motto><motto id="m225" man="周兴嗣">游鹍独运</motto><motto id="m226" man="周兴嗣">凌摩绛霄</motto><motto id="m227" man="周兴嗣">耽读玩市</motto><motto id="m228" man="周兴嗣">寓目囊箱</motto><motto id="m229" man="周兴嗣">易輶攸畏</motto><motto id="m230" man="周兴嗣">属耳垣墙</motto><motto id="m231" man="周兴嗣">具膳餐饭</motto><motto id="m232" man="周兴嗣">适口充肠</motto><motto id="m233" man="周兴嗣">饱饫烹宰</motto><motto id="m234" man="周兴嗣">饥厌糟糠</motto><motto id="m235" man="周兴嗣">亲戚故旧</motto><motto id="m236" man="周兴嗣">老少异粮</motto><motto id="m237" man="周兴嗣">妾御绩纺</motto><motto id="m238" man="周兴嗣">侍巾帷房</motto><motto id="m239" man="周兴嗣">纨扇圆絜</motto><motto id="m240" man="周兴嗣">银烛炜煌</motto><motto id="m241" man="周兴嗣">昼眠夕寐</motto><motto id="m242" man="周兴嗣">蓝笋象床</motto><motto id="m243" man="周兴嗣">弦歌酒宴</motto><motto id="m244" man="周兴嗣">接杯举觞</motto><motto id="m245" man="周兴嗣">矫手顿足</motto><motto id="m246" man="周兴嗣">悦豫且康</motto><motto id="m247" man="周兴嗣">嫡后嗣续</motto><motto id="m248" man="周兴嗣">祭祀烝尝</motto><motto id="m249" man="周兴嗣">稽颡再拜</motto><motto id="m250" man="周兴嗣">悚惧恐惶</motto><motto id="m251" man="周兴嗣">笺牒简要</motto><motto id="m252" man="周兴嗣">顾答审详</motto><motto id="m253" man="周兴嗣">骸垢想浴</motto><motto id="m254" man="周兴嗣">执热愿凉</motto><motto id="m255" man="周兴嗣">驴骡犊特</motto><motto id="m256" man="周兴嗣">骇跃超骧</motto><motto id="m257" man="周兴嗣">诛斩贼盗</motto><motto id="m258" man="周兴嗣">捕获叛亡</motto><motto id="m259" man="周兴嗣">布射僚丸</motto><motto id="m260" man="周兴嗣">嵇琴阮啸</motto><motto id="m261" man="周兴嗣">恬笔伦纸</motto><motto id="m262" man="周兴嗣">钧巧任钓</motto><motto id="m263" man="周兴嗣">释纷利俗</motto><motto id="m264" man="周兴嗣">竝皆佳妙</motto><motto id="m265" man="周兴嗣">毛施淑姿</motto><motto id="m266" man="周兴嗣">工颦妍笑</motto><motto id="m267" man="周兴嗣">年矢每催</motto><motto id="m268" man="周兴嗣">曦晖朗曜</motto><motto id="m269" man="周兴嗣">璇玑悬斡</motto><motto id="m270" man="周兴嗣">晦魄环照</motto><motto id="m271" man="周兴嗣">指薪修祜</motto><motto id="m272" man="周兴嗣">永绥吉劭</motto><motto id="m273" man="周兴嗣">矩步引领</motto><motto id="m274" man="周兴嗣">俯仰廊庙</motto><motto id="m275" man="周兴嗣">束带矜庄</motto><motto id="m276" man="周兴嗣">徘徊瞻眺</motto><motto id="m277" man="周兴嗣">孤陋寡闻</motto><motto id="m278" man="周兴嗣">愚蒙等诮</motto><motto id="m279" man="周兴嗣">谓语助者</motto><motto id="m280" man="周兴嗣">焉哉乎也</motto></mottos>
