<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE root [
<!ELEMENT root ANY>
<!ELEMENT node ANY>


<!ENTITY copyright "Paradise Lost For CJ All Rights Reserved">

<!ENTITY pl4cj SYSTEM "pl4cj.ent">

<!ATTLIST node 
id ID #REQUIRED
for IDREFS "b"
age CDATA #FIXED "18"
>
]>
<root>
	<node id="a">&copyright;</node>
	<node id="b">&copyright;</node>
	<node id="c">&pl4cj;</node>
	
	<node id="dadsf" age="18">&copyright;</node>
</root>